#pragma once

enum ExceptionCode {
	// interrupt exception codes (mcause)
	EXC_S_SOFTWARE_INTERRUPT = 1,
	EXC_VS_SOFTWARE_INTERRUPT = 2,
	EXC_M_SOFTWARE_INTERRUPT = 3,

	EXC_S_TIMER_INTERRUPT = 5,
	EXC_VS_TIMER_INTERRUPT = 6,
	EXC_M_TIMER_INTERRUPT = 7,

	EXC_S_EXTERNAL_INTERRUPT = 9,
	EXC_VS_EXTERNAL_INTERRUPT = 10,
	EXC_M_EXTERNAL_INTERRUPT = 11,

	EXC_S_GUEST_EXTERNAL_INTERRUPT = 12,

	EXC_COUNTER_OVREFLOW_INTERRUPT = 13,
	EXC_DEBUG_TRACE_INTERRUPT = 17,
	EXC_BUS_SYSTEM_ERROR_INTERRUPT = 23,
	EXC_LOW_PRIO_RAS_INTERRUPT = 35,
	EXC_HIGH_PRIO_RAS_INTERRUPT = 43,
	EXC_HP_OT_EVENT_INTERRUPT = 45,
	EXC_WDT_INTERRUPT = 48,

	// non-interrupt exception codes (mcause)
	EXC_INSTR_ADDR_MISALIGNED = 0,
	EXC_INSTR_ACCESS_FAULT = 1,
	EXC_ILLEGAL_INSTR = 2,
	EXC_BREAKPOINT = 3,
	EXC_LOAD_ADDR_MISALIGNED = 4,
	EXC_LOAD_ACCESS_FAULT = 5,
	EXC_STORE_AMO_ADDR_MISALIGNED = 6,
	EXC_STORE_AMO_ACCESS_FAULT = 7,

	EXC_ECALL_U_MODE = 8,
	EXC_ECALL_S_MODE = 9,
	EXC_ECALL_VS_MODE = 10,
	EXC_ECALL_M_MODE = 11,

	EXC_INSTR_PAGE_FAULT = 12,
	EXC_LOAD_PAGE_FAULT = 13,
	EXC_SMPU_MULTIPLE_TRANSLATIONS = 14,
	EXC_STORE_AMO_PAGE_FAULT = 15,

	EXC_SMPU_GUEST_MULTIPLE_TRANSLATIONS = 16, // TODO: Align this value with SMPU spec
	EXC_INSTR_GUEST_PAGE_FAULT = 20,
	EXC_LOAD_GUEST_PAGE_FAULT = 21,
	EXC_VIRTUAL_INSTRUCTION = 22,
	EXC_STORE_AMO_GUEST_PAGE_FAULT = 23,
};
